### ISSUE TITLE
Excuse me, can you provide the whole json files for run different models?

### ISSUE THREAD

**Issue by zhang-jinghua** [zhchuu/continual-learning-reproduce#2]

**Comment by zhchuu** [comment]
As mentioned on the README page, the JSON file is for global settings (e.g., model name, memory size, incremental strategy). Just modify the 'model_name' in the JSON file if you need to run a different model. I newly upload some examples to show how the JSON file works.

BTW: For every model, I have hard-coded some default hyperparameters provided by the paper in the corresponding files. Thus, adjusting these hyperparameters is needed if your experiment settings are different from the paper.

**Comment by zhang-jinghua** [comment]
many thx
