### ISSUE TITLE
Gradcam

### ISSUE THREAD

**Issue by koy030016** [zhchuu/continual-learning-reproduce#3]
Excuse me, is there a way to visualize the gradcam in lwm.py?

**Comment by zhchuu** [comment]
Although it is possible to visualize the Grad-cam, I will not include it in this repository as it is not closely related to reproducing the paper results. I have experience using Grad-cam in one of my other research projects (See [this](https://arxiv.org/abs/2108.05187)), and the code is stored in a private repository. If you require any assistance or guidance, please feel free to contact me via email.

chh.zhong[at]outlook[dot]com
